### ISSUE TITLE
make utility functions (`xml2ebml`, `ebml2xml`, etc.) CL utilities

### ISSUE THREAD

**Issue by CrepeGoat** [MideTechnology/ebmlite#44]
The setup.py script can be configured to turn the utility functions for this package (i.e., any of `xml2ebml`, `ebml2xml`, and `view`) into command-line utilities. The aim is to improve accessibility for these utilities. See links for details on how to do so:
- https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument
- https://docs.python.org/3/distutils/setupscript.html#installing-scripts

**Comment by CFlaniganMide** [comment]
Some brief looking into things, here's my proposed changes:
- Fix utils.py in place, fix the imports so that it can be imported in another file as ebmlite.utils.  This will not work as a command line utility.
- Create a new file in a separate module to use as a command line tool.
- Modify the directory structure as such:
  - \ebmlite\
    - \ebmlite\  # the actual regular ebmlite stuff
      - \utils.py  # assorted utility functions
    - \tests\  # just tests
    - \bin\  # command line utillities
      - \ebmlite_utils.py  # command line interface to ebmlite.utils that imports things correctly

**Comment by StokesMIDE** [comment]
Suggestion: if the utilities are going to be separated from `util.py`, they might as well be individual tools, e.g. `ebml2xml.py`, `xml2ebml.py`, and `ebmlview.py`.

**Comment by CFlaniganMide** [comment]
yeah, that would make the CLI easier to use.

**Comment by StokesMIDE** [comment]
I think this was resolved in PR #46.
